# Generated by Django 2.2.2 on 2020-01-24 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailleads',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
